apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kutt-pvc
  namespace: kutt
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
