apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: monitoring
spec:
  project: default

  source:
    repoURL: 'https://github.com/stephenntiri/argocd-kutt.git'
    targetRevision: HEAD
    path: argocd-kutt/loki-stack
  destination: 
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
