grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.k8stunde.local
prometheus:
  enabled: true
  isDefault: false
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.k8stunde.local